services:
  db:
    image: arm64v8/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  test-db:
    image: arm64v8/mysql
    env_file:
      - .env
    ports:
      - '3306:3307'
    volumes:
      - my-testdb:/var/lib/mysql-test

volumes:
  my-db:
  my-testdb:
